import About from "./about/About";
import Home from "./home/Home";
import Login from "./auth/Login";
import Register from "./auth/Register";
import Verify from "./auth/Verify";
import Account from "./account/Account";
import CourseDesc from "./courseDescription/CourseDesc";
import PaymentSuccess from "./payment-success/PaymentSuccess";
import Dashboard from "./dashboard/Dashboard";
import CourseStudy from "./coursestudy/CourseStudy";
import CourseEdit from "./CourseEdit/CourseEdit";
import AdminDashBoard from "../admin/dashboard/AdminDashBoard";
export { About,Home,Login,Register,Verify, Account,CourseDesc,PaymentSuccess,Dashboard,CourseStudy,CourseEdit,AdminDashBoard}